# for local development - do not use in production without modifications (ports exposed, etc.)
services:
  # PostgreSQL
  postgres-db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - backend
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FastAPI App
  app:
    build: .
    container_name: fastapi_app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      WATCHFILES_FORCE_POLLING: true
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - pip-cache:/root/.cache/pip
    depends_on:
      - postgres-db
      - redis
    networks:
      - backend

  # Celery Worker
  celery:
    build: .
    # container_name: celery_worker
    hostname: worker1
    # command: celery -A ${CELERY_MODULE}.celery_app worker -n worker@%h --loglevel=info
    command: /app/start_workers.sh ${CELERY_WORKERS} ${FEED_WORKERS} ${MODEL_WORKERS}
    environment:
      - CELERY_MODULE=${CELERY_MODULE}
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres-db
    networks:
      - backend

  # feed_worker:
  #   build: .
  #   command: celery -A ${CELERY_MODULE}.feed_worker.feed_worker_app worker -n feed_worker@%h --loglevel=info
  #   environment:
  #     - CELERY_MODULE=${CELERY_MODULE}
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis
  #     - postgres-db
  #   networks:
  #     - backend

  flower:
    container_name: flower
    build: .
    command: celery -A ${CELERY_MODULE}.worker.celery_app flower --port=5555
    ports:
      - "5556:5555"
    depends_on:
      - redis
      - postgres-db
      - celery
      - app
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  pip-cache: