FROM nvidia/cuda:12.6.0-runtime-ubuntu22.04

# RUN nvidia-smi

# # python 3.12
RUN sed -i 's|http://archive.ubuntu.com|https://archive.ubuntu.com|g' /etc/apt/sources.list && \
    sed -i 's|http://security.ubuntu.com|https://security.ubuntu.com|g' /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y python3-pip python3-dev python-is-python3 && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    gstreamer1.0-tools \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    gstreamer1.0-rtsp \
    gstreamer1.0-x \
    gstreamer1.0-gl \
    gstreamer1.0-vaapi \
    libgstreamer1.0-0 \
    libgstreamer-plugins-base1.0-0 \
    libgirepository-1.0-1 \
    gobject-introspection \
    gir1.2-gst-plugins-base-1.0 \
    gir1.2-gstreamer-1.0 \
    libsm6 libxext6 libgl1-mesa-glx \
    pkg-config libcairo2-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# requirements for backend
COPY requirements.txt .
RUN pip install --upgrade pip
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

# pytorch with gpu support
RUN --mount=type=cache,target=/root/.cache/pip pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126
# paddlepaddle with gpu support
# RUN --mount=type=cache,target=/root/.cache/pip pip install paddlepaddle-gpu==3.0.0 --index-url https://www.paddlepaddle.org.cn/packages/stable/cu126/
RUN --mount=type=cache,target=/root/.cache/pip pip install dill

# backend code and .env file
COPY backend/ ./backend
COPY .env /app/.env

# add scripts and make them executable
COPY start_workers.sh /app/start_workers.sh
RUN chmod +x /app/start_workers.sh

COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# add sample data for testing
COPY data/ /app/data
COPY /alert_images/ /app/alert_images

# expose port
EXPOSE 8000

# run fastapi server with reload, after waiting for postgres
WORKDIR /app/backend
CMD ["/wait-for-it.sh", "postgres:5432", "--timeout=5", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]