services:
  # PostgreSQL
  postgres-db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      backend:
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    networks:
      backend:
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FastAPI
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: fastapi_app
    environment:
      REDIS_URL: ${REDIS_URL}
      WATCHFILES_FORCE_POLLING: "true"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - pip-cache:/root/.cache/pip
      - ./alert_images:/app/alert_images
    depends_on:
      - postgres-db
      - redis
    networks:
      backend:
    runtime: nvidia

  # Celery Workers with gpu support
  celery:
    build:
      context: .
      dockerfile: Dockerfile.prod
    hostname: worker1
    command: /app/start_workers.sh ${CELERY_WORKERS} ${FEED_WORKERS} ${MODEL_WORKERS} ${STREAM_WORKERS}
    environment:
      - CELERY_MODULE=${CELERY_MODULE}
    volumes:
      - .:/app
      - pip-cache:/root/.cache/pip
      - ./alert_images:/app/alert_images
    depends_on:
      - redis
      - postgres-db
    networks:
      backend:
      stream-net:
        mac_address: D0:94:66:7E:8F:30
        ipv4_address: 172.23.55.189
    runtime: nvidia

  # Flower - for monitoring Celery workers
  flower:
    container_name: flower
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A ${CELERY_MODULE}.worker.celery_app -A ${CELERY_MODULE}.feed_worker.feed_worker_app -A ${CELERY_MODULE}.model_worker.model_worker_app flower --port=5555
    volumes:
      - .:/app
      - pip-cache:/root/.cache/pip
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - postgres-db
      - celery
      - app
    networks:
      backend:
    runtime: nvidia

networks:
  backend:
    driver: bridge
    external: false
  stream-net:
    driver: bridge
    external: true

volumes:
  postgres_data:
  pip-cache:
  alert_images: